using System;
using System.Collections.Generic;
using System.Text;

namespace BerryAP.Mappings
{
    class WallMapping
    {
        public static Dictionary<int, (int itemid, string internal_name, string ap_name)> mapping = new Dictionary<int, (int itemid, string internal_name, string ap_name)>
        {
            /// Mapping the breakable walls. Format is  Zone (AP ID, Internal Name, AP Name)
            /// Area 1 
            {0, (50, "FULL_BreakableWall", "Test") },
            {0, (50, "FULL_BreakableWall (1)", "Test") },
            {0, (50, "FULL_BreakableWall (2)", "Test") },
            {0, (50, "FULL_BreakableWall (3)", "Test") },
            {0, (50, "FULL_BreakableWall (4)", "Test") },
            {0, (50, "FULL_BreakableWall (5)", "Test") },
            {0, (50, "FULL_BreakableWall (6)", "Test") },
            {0, (50, "FULL_BreakableWall (7)", "Test") },
            {0, (50, "FULL_BreakableWall (8)", "Test") },
            {0, (50, "FULL_BreakableWall (9)", "Test") },
            {0, (50, "FULL_BreakableWall (10)", "Test") },
            {0, (50, "FULL_BreakableWall (11)", "Test") },
            {0, (50, "FULL_BreakableWall (12)", "Test") },
            {0, (50, "FULL_BreakableWall (13)", "Test") },
            {0, (50, "FULL_BreakableWall (14)", "Test") },
            {0, (50, "FULL_BreakableWall (15)", "Test") },
            {0, (50, "FULL_BreakableWall (16)", "Test") },
            {0, (50, "FULL_BreakableWall (19)", "Test") },
            {0, (50, "FULL_BreakableWall (20)", "Test") },
            {0, (50, "FULL_BreakableWall (21)", "Test") },

            /// Area 2
            {0, (50, "FULL_BreakableWall (50)", "Test") },
            {0, (50, "FULL_BreakableWall (51)", "Test") },
            {0, (50, "FULL_BreakableWall (52)", "Test") },
            {0, (50, "FULL_BreakableWall (53)", "Test") },
            {0, (50, "FULL_BreakableWall (54)", "Test") },
            {0, (50, "FULL_BreakableWall (55)", "Test") },
            {0, (50, "FULL_BreakableWall (56)", "Test") },
            {0, (50, "FULL_BreakableWall (57)", "Test") },
            {0, (50, "FULL_BreakableWall (58)", "Test") },
            {0, (50, "FULL_BreakableWall (59)", "Test") },
            {0, (50, "FULL_BreakableWall (60)", "Test") },
            {0, (50, "FULL_BreakableWall (61)", "Test") },
            {0, (50, "FULL_BreakableWall (62)", "Test") },
            {0, (50, "FULL_BreakableWall (63)", "Test") },
            {0, (50, "FULL_BreakableWall (64)", "Test") },
            {0, (50, "FULL_BreakableWall (65)", "Test") },
            {0, (50, "FULL_BreakableWall (66)", "Test") },
            {0, (50, "FULL_BreakableWall (67)", "Test") },
            {0, (50, "FULL_BreakableWall (68)", "Test") },
            {0, (50, "FULL_BreakableWall (69)", "Test") },
            {0, (50, "FULL_BreakableWall (70)", "Test") },
            {0, (50, "FULL_BreakableWall (71)", "Test") },
            {0, (50, "FULL_BreakableWall (72)", "Test") },
            {0, (50, "FULL_BreakableWall (127)", "Test") },
            {0, (50, "FULL_BreakableWall (165)", "Test") },
            {0, (50, "FULL_BreakableWall (166)", "Test") },
            {0, (50, "FULL_BreakableWall (167)", "Test") },
            {0, (50, "FULL_BreakableWall (168)", "Test") },
            {0, (50, "FULL_BreakableWall (169)", "Test") },
            {0, (50, "FULL_BreakableWall (172)", "Test") },
            {0, (50, "FULL_BreakableWall (173)", "Test") },
            {0, (50, "FULL_BreakableWall (193)", "Test") },

            /// Area 3
            {0, (50, "FULL_BreakableWall (212)", "Test") },
            {0, (50, "FULL_BreakableWall (176)", "Test") },
            {0, (50, "FULL_BreakableWall (108)", "Test") },
            {0, (50, "FULL_BreakableWall (107)", "Test") },
            {0, (50, "FULL_BreakableWall (93)", "Test") },
            {0, (50, "FULL_BreakableWall (92)", "Test") },
            {0, (50, "FULL_BreakableWall (88)", "Test") },
            {0, (50, "FULL_BreakableWall (89)", "Test") },
            {0, (50, "FULL_BreakableWall (90)", "Test") },
            {0, (50, "FULL_BreakableWall (091)", "Test") },
            {0, (50, "FULL_BreakableWall (092)", "Test") },
            {0, (50, "FULL_BreakableWall (093)", "Test") },
            {0, (50, "FULL_BreakableWall (214)", "Test") },
            {0, (50, "FULL_BreakableWall (178)", "Test") },
            {0, (50, "FULL_BreakableWall (171)", "Test") },
            {0, (50, "FULL_BreakableWall (109)", "Test") },
            {0, (50, "FULL_BreakableWall (98)", "Test") },
            {0, (50, "FULL_BreakableWall (102)", "Test") },
            {0, (50, "FULL_BreakableWall (97)", "Test") },
            {0, (50, "FULL_BreakableWall (101)", "Test") },
            {0, (50, "FULL_BreakableWall (96)", "Test") },
            {0, (50, "FULL_BreakableWall (100)", "Test") },
            {0, (50, "FULL_BreakableWall (95)", "Test") },
            {0, (50, "FULL_BreakableWall (99)", "Test") },
            {0, (50, "FULL_BreakableWall (94)", "Test") },
            {0, (50, "FULL_BreakableWall (103)", "Test") },
            {0, (50, "FULL_BreakableWall (180)", "Test") },
            {0, (50, "FULL_BreakableWall (215)", "Test") },
            {0, (50, "FULL_BreakableWall (213)", "Test") },
            {0, (50, "FULL_BreakableWall (175)", "Test") },
            {0, (50, "FULL_BreakableWall (104)", "Test") },
            {0, (50, "FULL_BreakableWall (78)", "Test") },
            {0, (50, "FULL_BreakableWall (75)", "Test") },
            {0, (50, "FULL_BreakableWall (74)", "Test") },
            {0, (50, "FULL_BreakableWall (76)", "Test") },
            {0, (50, "FULL_BreakableWall (77)", "Test") },
            {0, (50, "FULL_BreakableWall (79)", "Test") },
            {0, (50, "FULL_BreakableWall (105)", "Test") },
            {0, (50, "FULL_BreakableWall (174)", "Test") },
            {0, (50, "FULL_BreakableWall (209)", "Test") },
            {0, (50, "FULL_BreakableWall (210)", "Test") },
            {0, (50, "FULL_BreakableWall (179)", "Test") },
            {0, (50, "FULL_BreakableWall (106)", "Test") },
            {0, (50, "FULL_BreakableWall (73)", "Test") },
            {0, (50, "FULL_BreakableWall (80)", "Test") },
            {0, (50, "FULL_BreakableWall (81)", "Test") },
            {0, (50, "FULL_BreakableWall (82)", "Test") },
            {0, (50, "FULL_BreakableWall (83)", "Test") },
            {0, (50, "FULL_BreakableWall (84)", "Test") },
            {0, (50, "FULL_BreakableWall (85)", "Test") },
            {0, (50, "FULL_BreakableWall (86)", "Test") },
            {0, (50, "FULL_BreakableWall (87)", "Test") },
            {0, (50, "FULL_BreakableWall (91)", "Test") },
            {0, (50, "FULL_BreakableWall (170)", "Test") },
            {0, (50, "FULL_BreakableWall (177)", "Test") },
            {0, (50, "FULL_BreakableWall (211)", "Test") },

            /// Area 4
            {0, (50, "FULL_BreakableWall (222)", "Test") },
            {0, (50, "FULL_BreakableWall (139)", "Test") },
            {0, (50, "FULL_BreakableWall (142)", "Test") },
            {0, (50, "FULL_BreakableWall (143)", "Test") },
            {0, (50, "FULL_BreakableWall (145)", "Test") },
            {0, (50, "FULL_BreakableWall (144)", "Test") },
            {0, (50, "FULL_BreakableWall (147)", "Test") },
            {0, (50, "FULL_BreakableWall (148)", "Test") },
            {0, (50, "FULL_BreakableWall (203)", "Test") },
            {0, (50, "FULL_BreakableWall (223)", "Test") },
            {0, (50, "FULL_BreakableWall (224)", "Test") },
            {0, (50, "FULL_BreakableWall (225)", "Test") },
            {0, (50, "FULL_BreakableWall (233)", "Test") },
            {0, (50, "FULL_BreakableWall (232)", "Test") },
            {0, (50, "FULL_BreakableWall (231)", "Test") },
            {0, (50, "FULL_BreakableWall (230)", "Test") },
            {0, (50, "FULL_BreakableWall (229)", "Test") },
            {0, (50, "FULL_BreakableWall (228)", "Test") },
            {0, (50, "FULL_BreakableWall (227)", "Test") },
            {0, (50, "FULL_BreakableWall (226)", "Test") },
            {0, (50, "FULL_BreakableWall (152)", "Test") },
            {0, (50, "FULL_BreakableWall (151)", "Test") },
            {0, (50, "FULL_BreakableWall (150)", "Test") },
            {0, (50, "FULL_BreakableWall (204)", "Test") },
            {0, (50, "FULL_BreakableWall (149)", "Test") },
            {0, (50, "FULL_BreakableWall (205)", "Test") },
            {0, (50, "FULL_BreakableWall (206)", "Test") },
            {0, (50, "FULL_BreakableWall (207)", "Test") },
            {0, (50, "FULL_BreakableWall (208)", "Test") },
            {0, (50, "FULL_BreakableWall (220)", "Test") },
            {0, (50, "FULL_BreakableWall (234)", "Test") },
            {0, (50, "FULL_BreakableWall (197)", "Test") },
            {0, (50, "FULL_BreakableWall (192)", "Test") },
            {0, (50, "FULL_BreakableWall (191)", "Test") },
            {0, (50, "FULL_BreakableWall (164)", "Test") },
            {0, (50, "FULL_BreakableWall (161)", "Test") },
            {0, (50, "FULL_BreakableWall (163)", "Test") },
            {0, (50, "FULL_BreakableWall (158)", "Test") },
            {0, (50, "FULL_BreakableWall (160)", "Test") },
            {0, (50, "FULL_BreakableWall (157)", "Test") },
            {0, (50, "FULL_BreakableWall (159)", "Test") },
            {0, (50, "FULL_BreakableWall (154)", "Test") },
            {0, (50, "FULL_BreakableWall (153)", "Test") },
            {0, (50, "FULL_BreakableWall (156)", "Test") },
            {0, (50, "FULL_BreakableWall (155)", "Test") },
            {0, (50, "FULL_BreakableWall (124)", "Test") },
            {0, (50, "FULL_BreakableWall (125)", "Test") },
            {0, (50, "FULL_BreakableWall (110)", "Test") },
            {0, (50, "FULL_BreakableWall (111)", "Test") },
            {0, (50, "FULL_BreakableWall (187)", "Test") },
            {0, (50, "FULL_BreakableWall (188)", "Test") },
            {0, (50, "FULL_BreakableWall (189)", "Test") },
            {0, (50, "FULL_BreakableWall (218)", "Test") },
            {0, (50, "FULL_BreakableWall (219)", "Test") },
            {0, (50, "FULL_BreakableWall (186)", "Test") },
            {0, (50, "FULL_BreakableWall (185)", "Test") },
            {0, (50, "FULL_BreakableWall (184)", "Test") },
            {0, (50, "FULL_BreakableWall (121)", "Test") },
            {0, (50, "FULL_BreakableWall (120)", "Test") },
            {0, (50, "FULL_BreakableWall (115)", "Test") },
            {0, (50, "FULL_BreakableWall (114)", "Test") },
            {0, (50, "FULL_BreakableWall (113)", "Test") },
            {0, (50, "FULL_BreakableWall (112)", "Test") },
            {0, (50, "FULL_BreakableWall (116)", "Test") },
            {0, (50, "FULL_BreakableWall (117)", "Test") },
            {0, (50, "FULL_BreakableWall (118)", "Test") },
            {0, (50, "FULL_BreakableWall (119)", "Test") },
            {0, (50, "FULL_BreakableWall (122)", "Test") },
            {0, (50, "FULL_BreakableWall (123)", "Test") },
            {0, (50, "FULL_BreakableWall (181)", "Test") },
            {0, (50, "FULL_BreakableWall (182)", "Test") },
            {0, (50, "FULL_BreakableWall (183)", "Test") },
            {0, (50, "FULL_BreakableWall (217)", "Test") },
            {0, (50, "FULL_BreakableWall (216)", "Test") },
            {0, (50, "FULL_BreakableWall (202)", "Test") },
            {0, (50, "FULL_BreakableWall (201)", "Test") },
            {0, (50, "FULL_BreakableWall (200)", "Test") },
            {0, (50, "FULL_BreakableWall (199)", "Test") },
            {0, (50, "FULL_BreakableWall (126)", "Test") },
            {0, (50, "FULL_BreakableWall (129)", "Test") },
            {0, (50, "FULL_BreakableWall (128)", "Test") },
            {0, (50, "FULL_BreakableWall (132)", "Test") },
            {0, (50, "FULL_BreakableWall (130)", "Test") },
            {0, (50, "FULL_BreakableWall (133)", "Test") },
            {0, (50, "FULL_BreakableWall (131)", "Test") },
            {0, (50, "FULL_BreakableWall (136)", "Test") },
            {0, (50, "FULL_BreakableWall (134)", "Test") },
            {0, (50, "FULL_BreakableWall (137)", "Test") },
            {0, (50, "FULL_BreakableWall (135)", "Test") },
            {0, (50, "FULL_BreakableWall (140)", "Test") },
            {0, (50, "FULL_BreakableWall (138)", "Test") },
            {0, (50, "FULL_BreakableWall (141)", "Test") },
            {0, (50, "FULL_BreakableWall (198)", "Test") },
            {0, (50, "FULL_BreakableWall (194)", "Test") },
            {0, (50, "FULL_BreakableWall (195)", "Test") },
            {0, (50, "FULL_BreakableWall (196)", "Test") },
            {0, (50, "FULL_BreakableWall (221)", "Test") },
            {0, (50, "FULL_BreakableWall (190)", "Test") },

            /// Secret Wall
            {0, (50, "FULL_BreakableWall_Secret", "Test") }

        };
    }
}
